export const LOGIN_SCREEN = "LOGIN_SCREEN";
export const PROFILE_SCREEN = "PROFILE_SCREEN";
export const SIGNUP_SCREEN = "SIGNUP_SCREEN";
export const POST_SCREEN = "POST_SCREEN";
export const ADD_SCREEN = "ADD_SCREEN";